spring.datasource.url=jdbc:postgresql://localhost:5432/kairos_db
spring.datasource.username=kairos
spring.datasource.password=kairos123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

server.port=8080

# JWT
jwt.secret=${JWT_SECRET:cambia-esta-clave-secreta-de-32-caracteres-min}
jwt.expiration-ms=3600000

